import type { ReasoningEffortValue } from "./reasoning-effort";

export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "audio" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** Electron inbox only: originating channel, e.g. "telegram", "discord". */
  sourceChannel?: string;
  /** Heartbeat/cron 等主动投递到会话、前面没有 user 消息的 assistant 行。 */
  channelDelivery?: boolean;
  /** 用户在本轮通过 message 工具外发到其他通道的镜像行（数据区分；徽章仍可与主动推送并存）。 */
  userInitiatedDelivery?: boolean;
  /** cron / heartbeat 主动投递来源任务 id。 */
  cronJobId?: string;
  /** cron / heartbeat 主动投递来源任务名（heartbeat 存字面量，UI 特判 i18n）。 */
  cronJobName?: string;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** Structured tool events behind trace rows. Kept so activity cards can
   * distinguish running, completed, and failed tool phases. */
  toolEvents?: ToolProgressEvent[];
  /** Activity rows: explicit file edits emitted by edit tools. */
  fileEdits?: UIFileEdit[];
  /** Activity rows created during the same agent phase share one collapsible block. */
  activitySegmentId?: string;
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** 后端已将本条消息的音频交给 THA，Electron 不再本地自动播放。 */
  thaPlayed?: boolean;
  /** App-specific CLI adapters explicitly attached to this user turn. */
  cliApps?: UICliAppAttachment[];
  /** Settings-managed MCP presets explicitly attached to this user turn. */
  mcpPresets?: UIMcpPresetAttachment[];
  /** Assistant turn: accumulated model reasoning / thinking text. Built up
   * incrementally from ``reasoning_delta`` frames; finalized when
   * ``reasoning_end`` arrives. */
  reasoning?: string;
  /** True while ``reasoning_delta`` frames are still arriving for this turn.
   * Drives the shimmer header on ``ReasoningBubble``. */
  reasoningStreaming?: boolean;
  /** User turn: auxiliary vision caption still streaming from ``vision_caption_*`` frames. */
  visionCaptionStreaming?: boolean;
  /** End-to-end wall time for this assistant turn (persisted ``latency_ms`` / ``turn_end``). */
  latencyMs?: number;
  /** Token usage for this assistant turn (from ``turn_end`` / persisted ``usage`` field). */
  usage?: TurnUsageStats;
  /** Wall-clock timestamp of the assistant message (ISO local-time string from backend, or ms epoch for live turns). */
  messageTs?: string | number;
  /** Assistant message-bound TTS playback segments, persisted in WebUI transcript. */
  playbackSegments?: AssistantPlaybackSegment[];
}

/** Per-turn token stats: last-call context size vs turn-total billing. */
export interface TurnUsageStats {
  /** Last LLM call input size (↑ display; context at this message cutoff). */
  last_prompt_tokens?: number;
  /** Sum of prompt_tokens across all LLM calls this turn (tooltip / billing). */
  turn_prompt_tokens?: number;
  /** Sum of completion_tokens this turn (↓ display). */
  turn_completion_tokens?: number;
  last_cached_tokens?: number;
  turn_cached_tokens?: number;
  /** Estimated prompt size at cutoff (system + tools + history); drives ctx%. */
  context_tokens?: number;
  context_pct?: number;
  /** @deprecated Pre-split saves: accumulated prompt_tokens only. */
  prompt_tokens?: number;
  completion_tokens?: number;
  cached_tokens?: number;
}

export interface UICliAppAttachment {
  name: string;
  display_name?: string;
  category?: string;
  entry_point?: string;
  logo_url?: string | null;
  brand_color?: string | null;
}

export interface UIMcpPresetAttachment {
  name: string;
  display_name?: string;
  category?: string;
  transport?: string;
  status?: string;
  configured?: boolean;
  logo_url?: string | null;
  brand_color?: string | null;
}

/** Structured UI blob on ``progress`` WS frames; channels may add more ``kind`` values later. */
export interface AgentUIBlob {
  kind: string;
  data?: unknown;
}

/** WebSocket snapshot for sustained goals (`goal_state` events; keyed by ``chat_id``). */
export interface GoalStateWsPayload {
  active: boolean;
  ui_summary?: string;
  objective?: string;
}

export interface ToolProgressEvent {
  version?: number;
  phase?: "start" | "end" | "error" | string;
  call_id?: string;
  name?: string;
  arguments?: unknown;
  result?: unknown;
  error?: unknown;
  files?: unknown[];
  embeds?: unknown[];
}

export interface UIFileDiff {
  format: "unified" | string;
  context?: number;
  truncated?: boolean;
  text?: string;
}

export interface UIFileEdit {
  version?: number;
  call_id: string;
  tool: string;
  path: string;
  absolute_path?: string;
  phase?: "start" | "end" | "error" | string;
  added: number;
  deleted: number;
  approximate?: boolean;
  status: "editing" | "done" | "error";
  binary?: boolean;
  error?: string;
  pending?: boolean;
  operation?: "edit" | "delete" | string;
  diff?: UIFileDiff;
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  title?: string;
  preview: string;
  /** Unix epoch seconds when this session currently has a turn in flight. */
  runStartedAt?: number | null;
}

export type SidebarDensity = "comfortable" | "compact";
export type SidebarSortMode = "updated_desc" | "created_desc" | "title_asc";

export interface SidebarViewState {
  density: SidebarDensity;
  show_previews: boolean;
  show_timestamps: boolean;
  show_archived: boolean;
  sort: SidebarSortMode;
}

export interface SidebarStatePayload {
  schema_version: number;
  pinned_keys: string[];
  archived_keys: string[];
  title_overrides: Record<string, string>;
  tags_by_key: Record<string, string[]>;
  collapsed_groups: Record<string, boolean>;
  view: SidebarViewState;
  updated_at?: string | null;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
}

export interface SettingsPayload {
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
    model_preset: string | null;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
    timezone: string;
    bot_name: string;
    bot_icon: string;
    bot_avatar_url: string | null;
    tool_hint_max_length: number;
    vision_model?: string | null;
    vision_provider?: string | null;
    max_messages?: number;
  };
  model_presets: Array<{
    name: string;
    label: string;
    active: boolean;
    is_default: boolean;
    model: string;
    provider: string;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
    vision_model: string | null;
    vision_provider: string | null;
  }>;
  providers: Array<{
    name: string;
    label: string;
    configured: boolean;
    api_key_required?: boolean;
    api_key_hint?: string | null;
    api_base?: string | null;
    default_api_base?: string | null;
    api_type?: "auto" | "chat_completions" | "responses";
  }>;
  web_search: {
    provider: string;
    api_key_hint?: string | null;
    base_url?: string | null;
    max_results: number;
    timeout: number;
    providers: Array<{
      name: string;
      label: string;
      credential: "none" | "api_key" | "base_url";
    }>;
  };
  web: {
    enable: boolean;
    proxy?: string | null;
    user_agent?: string | null;
    search: {
      max_results: number;
      timeout: number;
    };
    fetch: {
      use_jina_reader: boolean;
    };
  };
  image_generation: {
    enabled: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    default_aspect_ratio: string;
    default_image_size: string;
    max_images_per_turn: number;
    save_dir: string;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
    }>;
  };
  deskPet: {
    tha: {
      config: {
        enabledEmotions: boolean;
        enabledMouthSync: boolean;
        windowWidth: number;
        windowHeight: number;
        audioDelayMs: number;
      };
      model: ThaModel;
      motions: string[];
      emotions: string[];
    };
    psb: {
      autoShow: boolean;
      selectedModelId: string | null;
      followMouse: boolean;
      enabledResponseTags: boolean;
      models: PsbModelSummary[];
    };
  };
  tts: {
    enabled: boolean;
    message_playback_enabled: boolean;
    default_voice: string;
    provider: string;
    model: string;
  };
  runtime: {
    config_path: string;
    workspace_path: string;
    gateway_host: string;
    gateway_port: number;
    heartbeat: {
      enabled: boolean;
      interval_s: number;
      keep_recent_messages: number;
      context_messages: number;
    };
    dream: {
      schedule: string;
      max_batch_size: number;
      max_iterations: number;
      annotate_line_ages: boolean;
    };
    unified_session: boolean;
  };
  advanced: {
    restrict_to_workspace: boolean;
    ssrf_whitelist_count: number;
    mcp_server_count: number;
    exec_enabled: boolean;
    exec_sandbox?: string | null;
    exec_path_append_set: boolean;
  };
  requires_restart: boolean;
  restart_required_sections?: Array<"runtime" | "web" | "image">;
}

export interface AppPackageRef {
  manager: string;
  name?: string;
}

export interface AppCapability {
  type: "cli" | "mcp" | "skill" | string;
  entry_point?: string;
  package?: AppPackageRef;
  path?: string;
  transport?: string;
  command?: string;
  args?: string[];
  url?: string;
  fields?: Array<{
    name: string;
    target?: string;
    required?: boolean;
    secret?: boolean;
    env_var?: string | null;
  }>;
}

export interface AppPlan {
  supported: boolean;
  strategy?: string;
  managed_paths?: string[];
  verification?: string[];
}

export interface AppTrust {
  registry: string;
  level: string;
  review_status: string;
}

export interface AppManifest {
  schema: "agent-app.v1" | string;
  id: string;
  display_name: string;
  version?: string;
  description: string;
  category: string;
  source: string;
  logo_url?: string | null;
  brand_color?: string | null;
  docs_url?: string | null;
  capabilities: AppCapability[];
  install: AppPlan;
  remove: AppPlan;
  trust: AppTrust;
}

export interface CliAppInfo {
  name: string;
  display_name: string;
  category: string;
  description: string;
  requires: string;
  source: string;
  entry_point: string;
  install_supported: boolean;
  installed: boolean;
  available: boolean;
  status: "installed" | "missing" | "available" | "unsupported" | "not_installed" | string;
  logo_url?: string | null;
  brand_color?: string | null;
  skill_installed: boolean;
  manifest?: AppManifest;
}

export interface CliAppsPayload {
  apps: CliAppInfo[];
  installed_count: number;
  catalog_updated_at?: string | null;
  last_action?: {
    ok: boolean;
    message: string;
    installed?: boolean;
    removed?: boolean;
    output?: string | null;
    still_available?: boolean;
    verification?: string[];
    verification_failed?: string[];
  };
}

export interface McpPresetField {
  name: string;
  label: string;
  secret: boolean;
  required: boolean;
  configured: boolean;
  placeholder?: string;
  env_var?: string | null;
}

export interface McpPresetInfo {
  name: string;
  display_name: string;
  category: string;
  description: string;
  docs_url: string;
  transport: "stdio" | "streamableHttp" | "sse" | "oauth" | string;
  requires: string;
  note: string;
  install_supported: boolean;
  installed: boolean;
  configured: boolean;
  available: boolean;
  status: "not_installed" | "configured" | "missing_credentials" | "missing_dependency" | "coming_soon" | string;
  logo_url?: string | null;
  brand_color?: string | null;
  required_fields: McpPresetField[];
  connection_summary: string;
  tool_count?: number;
  tool_names?: string[];
  checked_at?: string | null;
  error?: string | null;
  enabled_tools?: string[];
  source?: "preset" | "custom" | string;
  manifest?: AppManifest;
}

export interface McpPresetsPayload {
  presets: McpPresetInfo[];
  installed_count: number;
  requires_restart?: boolean;
  hot_reload?: {
    ok: boolean;
    message: string;
    added?: string[];
    changed?: string[];
    removed?: string[];
    retried?: string[];
    connected?: string[];
    configured?: string[];
    failed?: string[];
    tools_removed?: number;
    requires_restart?: boolean;
  };
  last_action?: {
    ok: boolean;
    message: string;
    installed?: boolean;
    removed?: boolean;
    managed_paths_removed?: string[];
    verification?: string[];
    verification_failed?: string[];
    tool_count?: number;
    tool_names?: string[];
    checked_at?: string | null;
    error?: string | null;
  };
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
  modelPreset?: string | null;
  timezone?: string;
  botName?: string;
  botIcon?: string;
  toolHintMaxLength?: number;
  visionModel?: string | null;
  visionProvider?: string | null;
  maxTokens?: number;
  contextWindowTokens?: number;
  maxMessages?: number;
  reasoningEffort?: ReasoningEffortValue;
}

export interface ModelConfigurationCreate {
  name?: string;
  label: string;
  provider: string;
  model: string;
  reasoningEffort?: ReasoningEffortValue;
}

export interface ProviderSettingsUpdate {
  provider: string;
  apiKey?: string;
  apiBase?: string;
  apiType?: "auto" | "chat_completions" | "responses";
}

export interface WebSearchSettingsUpdate {
  provider: string;
  apiKey?: string;
  baseUrl?: string;
  maxResults?: number;
  timeout?: number;
  useJinaReader?: boolean;
}

export interface ImageGenerationSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
  defaultAspectRatio: string;
  defaultImageSize: string;
  maxImagesPerTurn: number;
}

export interface ThaModel {
  id: string;
  name: string;
  available: boolean;
  format: "" | "onnx" | "mlpackage";
  path: string;
}

export interface ThaSettingsUpdate {
  enabledEmotions?: boolean;
  enabledMouthSync?: boolean;
  windowWidth?: number;
  windowHeight?: number;
  audioDelayMs?: number;
}

export interface PsbInitialState {
  timeline: string;
  expression: string;
  face: Record<string, number>;
  fade: Record<string, number>;
}

export interface PsbModelDetail {
  modelId: string;
  name: string;
  format: string;
  compatible: boolean;
  parseError?: string | null;
  translationStatus?: string;
  hasFaceTalk?: boolean;
  psbFile?: string;
  timelines: Array<{ label: string; labelZh?: string; looping?: boolean }>;
  expressions: Array<{ label: string; labelZh?: string }>;
  faceVariables: Array<{
    label: string;
    labelZh?: string;
    frames?: Array<{ label: string; labelZh?: string; value: number }>;
  }>;
  fadeVariables: Array<{
    label: string;
    labelZh?: string;
    frames?: Array<{ label: string; labelZh?: string; value: number }>;
  }>;
  initialState: PsbInitialState;
}

export interface PsbModelSummary {
  modelId: string;
  name: string;
  format: string;
  compatible: boolean;
  parseError?: string | null;
  translationStatus?: string;
  hasFaceTalk?: boolean;
}

export interface PsbSettingsUpdate {
  autoShow?: boolean;
  selectedModelId?: string | null;
  followMouse?: boolean;
  enabledResponseTags?: boolean;
}

export interface SlashCommand {
  command: string;
  title: string;
  description: string;
  icon: string;
  argHint?: string;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export interface AssistantPlaybackSegment {
  messageId: string;
  segmentIndex: number;
  rawText: string;
  controls?: Array<{ kind?: string; type: string; payload?: Record<string, unknown> }>;
  debug?: Record<string, unknown>;
  audio?: {
    status: "idle" | "pending" | "ready" | "playing" | "done" | "failed" | "skipped";
    url?: string;
    name?: string;
    mimeType?: string;
    error?: string;
  };
}

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      tha_played?: boolean;
      tool_events?: ToolProgressEvent[];
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress" | "reasoning";
      /** Server-measured turn wall time when this frame finishes an assistant reply. */
      latency_ms?: number;
      /** Optional structured payload on progress frames (channel-specific). */
      agent_ui?: AgentUIBlob;
      /** Electron inbox only: originating channel for inbox:unified fan-out. */
      source_channel?: string;
      source_chat_id?: string;
      /** Heartbeat/cron 等主动投递，UI 上不与上一轮 assistant 合并。 */
      channel_delivery?: boolean;
      /** 用户触发的跨通道外发镜像（数据区分，供重放保留）。 */
      user_initiated_delivery?: boolean;
      /** cron / heartbeat 主动投递来源任务 id。 */
      cron_job_id?: string;
      /** cron / heartbeat 主动投递来源任务名。 */
      cron_job_name?: string;
    }
  | {
      event: "user";
      chat_id: string;
      text?: string;
      media_urls?: Array<{ url: string; name?: string }>;
      /** Electron inbox only: originating channel for inbox:unified fan-out. */
      source_channel?: string;
      source_chat_id?: string;
    }
  | {
      event: "file_edit";
      chat_id: string;
      edits: UIFileEdit[];
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
      source_channel?: string;
      source_chat_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
      text?: string;
      source_channel?: string;
      source_chat_id?: string;
    }
  | {
      event: "assistant_playback_segment";
      chat_id: string;
      segment: AssistantPlaybackSegment;
    }
  | {
      event: "reasoning_delta";
      chat_id: string;
      text: string;
      stream_id?: string;
      source_channel?: string;
      source_chat_id?: string;
    }
  | {
      event: "reasoning_end";
      chat_id: string;
      stream_id?: string;
      source_channel?: string;
      source_chat_id?: string;
    }
  | {
      event: "vision_caption_delta";
      chat_id: string;
      text: string;
      image_index?: number;
      stream_id?: string;
      source_channel?: string;
      source_chat_id?: string;
    }
  | {
      event: "vision_caption_end";
      chat_id: string;
      image_index?: number;
      stream_id?: string;
      text?: string;
      error?: string;
      source_channel?: string;
      source_chat_id?: string;
    }
  | {
      event: "runtime_model_updated";
      model_name: string;
      model_preset?: string | null;
    }
  | {
      event: "turn_end";
      chat_id: string;
      latency_ms?: number;
      /** Authoritative sustained-goal snapshot for this chat (same shape as ``goal_state`` events). */
      goal_state?: GoalStateWsPayload;
      usage?: TurnUsageStats;
      source_channel?: string;
      source_chat_id?: string;
    }
  | {
      event: "goal_status";
      chat_id: string;
      /** Turn executing (user message through agent loop). */
      status: "running" | "idle";
      /** Server ``time.time()`` when ``status`` is ``running``. */
      started_at?: number;
    }
  | {
      event: "goal_state";
      chat_id: string;
      goal_state: GoalStateWsPayload;
    }
  | { event: "session_updated"; chat_id: string; scope?: "metadata" | "thread" | string }
  | { event: "error"; chat_id?: string; detail?: string }
  | { event: "screenshot_request"; request_id: string };

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export interface OutboundImageGeneration {
  enabled: true;
  aspect_ratio?: string | null;
}

export interface OutboundCliAppMention {
  name: string;
  display_name?: string;
  category?: string;
  entry_point?: string;
  logo_url?: string | null;
  brand_color?: string | null;
}

export interface OutboundMcpPresetMention {
  name: string;
  display_name?: string;
  category?: string;
  transport?: string;
  status?: string;
  configured?: boolean;
  logo_url?: string | null;
  brand_color?: string | null;
}

/** Response shape for ``GET .../webui-thread`` (server-built transcript replay). */
export interface WebuiThreadPersistedPayload {
  schemaVersion: number;
  sessionKey?: string;
  savedAt?: string;
  messages: UIMessage[];
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | { type: "presence"; focused: boolean }
  | { type: "screenshot_result"; request_id: string; data: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      image_generation?: OutboundImageGeneration;
      cli_apps?: OutboundCliAppMention[];
      mcp_presets?: OutboundMcpPresetMention[];
      /** Marks messages sent by the embedded WebUI, without changing the
       * generic websocket protocol for other clients. */
      webui?: true;
    };
